---
version: "2.1"
services:
  swag:
    # image: lscr.io/linuxserver/swag:latest
    image: lscr.io/linuxserver/nginx:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # - URL=yourdomain.lan
      # - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - EMAIL= #optional
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS= #optional
      # - STAGING=false #optional
    volumes:
      # - ./swag-config:/config
      - ./swag-scripts:/scripts
      - ./apk-cache:/etc/apk/cache
      # - ./ModSecurity:/opt/ModSecurity
    ports:
      - 4443:443
      - 480:80 #optional
    restart: unless-stopped
